#version: '3.8'

networks:
  AI-platform:
    driver: bridge

volumes:
  hadoop_namenode:
  hadoop_datanode1:
  mysql_data:
  redis_data:

services:
  # ========== Hadoop（单DataNode） ==========
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    hostname: namenode
    restart: always
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_replication=1
      - HDFS_CONF_dfs_namenode_name_dir=/hadoop/dfs/name
    env_file:
      - ./.env
    networks:
      - AI-platform

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    hostname: datanode1
    restart: always
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data
    environment:
      - SERVICE_PRECONDITION=namenode:9870
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_replication=1
      - HDFS_CONF_dfs_datanode_data_dir=/hadoop/dfs/data
    env_file:
      - ./.env
    networks:
      - AI-platform


  # ========== Spark ==========
  spark-master:
    image: apache/spark:3.5.5
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_WEBUI_PORT=8080
    networks:
      - AI-platform
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]   # 新增


  spark-worker:
    image: apache/spark:3.5.5
    container_name: spark-worker
    hostname: spark-worker
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1024M
      - SPARK_WORKER_CORES=1
    networks:
      - AI-platform
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]  # 新

  # ========== MySQL ==========
  mysql:
    image: mysql:8.0
    container_name: mysql
    hostname: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-sql123}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-modelTrainDB}
      MYSQL_USER: ${MYSQL_USER:-modelmanager}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-sql123}
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - AI-platform

  # ========== Redis ==========
  redis:
    image: redis:7-alpine
    container_name: redis
    hostname: redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD:-red123}
    volumes:
      - redis_data:/data
    networks:
      - AI-platform