server {
    listen 80;
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
    location /api/user/ {
        proxy_pass http://user_svc:8000/api/user/;
    }
    location /api/forum/ {
        proxy_pass http://user_svc:8000/api/forum/;
    }
    location /api/training/ {
        proxy_pass http://train_svc:8000/api/training/;
    }
    location /api/files/ {
        proxy_pass http://train_svc:8000/api/files/;
    }
    location /api/agent/ {
        proxy_pass http://agent_svc:8000/api/agent/;
    }
}