# Generated by Django 4.2.30 on 2026-04-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=64, unique=True)),
                ('model_type', models.CharField(max_length=50)),
                ('hidden_layer_sizes', models.IntegerField()),
                ('max_iter', models.IntegerField()),
                ('learning_rate', models.FloatField()),
                ('data_path', models.TextField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('final_error', models.FloatField(blank=True, null=True)),
                ('final_accuracy', models.FloatField(blank=True, null=True)),
                ('final_mae', models.FloatField(blank=True, null=True)),
                ('model_save_path', models.TextField(blank=True, null=True)),
                ('training_log_path', models.TextField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'training_records',
                'managed': False,
            },
        ),
    ]
