# Generated by Django 6.0.2 on 2026-04-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(max_length=50)),
                ('hidden_layer_sizes', models.IntegerField()),
                ('max_iter', models.IntegerField()),
                ('learning_rate', models.FloatField()),
                ('data_path', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=20)),
                ('metrics', models.JSONField(default=dict)),
                ('training_duration', models.FloatField(null=True)),
                ('data_loading_duration', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('can_download', models.BooleanField(default=True)),
            ],
        ),
    ]
